In [21]:
import pandas as pd
from pathlib import Path

rb_std_season_file = Path('data/rb_standard_season_2020.csv')
rb_std_pg_file = Path('data/rb_standard_pergame_2020.csv')
rb_adv_file = Path('data/rb_advanced_2020.csv')

rb_std_season_df = pd.read_csv(rb_std_season_file, index_col='ID')
rb_std_season_df.drop(['Rk'], axis=1, inplace=True)

rb_std_pg_df = pd.read_csv(rb_std_pg_file, index_col='ID')
rb_std_pg_df.drop(['Rk','Player','Tm','Age','Pos','G','GS','Y/A','Y/G'], axis=1, inplace=True)
rb_std_pg_df.columns = ['Att/G', 'Yds/G', 'TD/G', '1D/G', 'Lng/G', 'Fmb/G']

rb_adv_df = pd.read_csv(rb_adv_file, index_col='ID')
rb_adv_df.drop(['Rk','Player','Tm','Age','Pos','G','GS','Att','Yds','1D'], axis=1, inplace=True)

rb_all = pd.concat([rb_std_season_df, rb_std_pg_df, rb_adv_df], axis=1)
rb_all['Player'] = rb_all['Player'].str.replace('[\*\+]', '', regex=True)
rb_all.head(10)

,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,...,TD/G,1D/G,Lng/G,Fmb/G,YBC,YBC/Att,YAC,YAC/Att,BrkTkl,Att/Br
ID,,,,,,,,,,,,,,,,,,,,,
HenrDe00,Derrick Henry,TEN,26,RB,16,16,378,2027,17,98,...,1.06,6.13,94,0.19,954,2.5,1073,2.8,34,11.1
CookDa01,Dalvin Cook,MIN,25,RB,14,14,312,1557,16,91,...,1.14,6.50,70,0.36,801,2.6,756,2.4,33,9.5
JacoJo01,Josh Jacobs,LVR,22,RB,15,15,273,1065,12,61,...,0.80,4.07,28,0.13,525,1.9,540,2.0,20,13.7
MontDa01,David Montgomery,CHI,23,RB,15,14,247,1070,8,59,...,0.53,3.93,80,0.07,480,1.9,590,2.4,29,8.5
ElliEz00,Ezekiel Elliott,DAL,25,RB,15,15,244,979,6,62,...,0.40,4.13,31,0.40,458,1.9,521,2.1,15,16.3
RobiJa00,James Robinson,JAX,22,RB,14,14,240,1070,7,54,...,0.50,3.86,47,0.21,455,1.9,615,2.6,16,15.0
DrakKe00,Kenyan Drake,ARI,26,RB,15,13,239,955,10,59,...,0.67,3.93,69,0.20,549,2.3,406,1.7,16,14.9
TaylJo02,Jonathan Taylor,IND,21,RB,15,13,232,1169,11,69,...,0.73,4.60,62,0.07,690,3.0,479,2.1,15,15.5
GordMe00,Melvin Gordon,DEN,27,RB,15,10,215,986,9,46,...,0.60,3.07,65,0.27,530,2.5,456,2.1,16,13.4
JoneAa00,Aaron Jones,GNB,26,RB,14,14,201,1104,9,52,...,0.64,3.71,77,0.14,512,2.5,592,2.9,14,14.4